exclude: [README.md, content/README.md, content/CNAME]
keep_files: [CNAME, README.md, .git, .gitignore]

title: Центральный профессиональный союз промышленных альпинистов Российской Федерации
title_short: Профсоюз промышленных альпинистов РФ
description: Официальный сайт Центрального профессионального союза промышленных альпинистов Российской Федерации. Документы и новости организации и сообщества в целом.

description_short: Документы и новости организации и сообщества в целом.

keywords: промышленный альпинизм, промальп, промальпинизм, высотные работы, професиональный союз, профсоюз, rope access

email: profalp@goodclimbers.ru

baseurl: "/"
url: "http://profalp.goodclimbers.ru"

markdown: kramdown

source:       .
destination:  deploy

timezone: Europe/Moscow

lessc: /home/cat/.npm-global/bin/lessc

kramdown:
    auto_ids: false
