exclude:
    - README.md
    - content/README.md
    - content/CNAME
    - fonts/md-webfont/scss
    - fonts/md-webfont/css/materialdesignicons.css
    - fonts/md-webfont/css/materialdesignicons.css.map
    - fonts/md-webfont/css/materialdesignicons.min.css.map
    - fonts/md-webfont/.git
    - fonts/md-webfont/bower.json
    - fonts/md-webfont/license.txt
    - fonts/md-webfont/package.json
    - fonts/md-webfont/preview.html
    - fonts/md-webfont/README.md
keep_files:
    - CNAME
    - README.md
    - .git
    - .gitignore]

title: Центральный профессиональный союз промышленных альпинистов Российской Федерации
title_short: Профсоюз промышленных альпинистов РФ
description: Официальный сайт профсоюза. Документы и новости организации и сообщества в целом.

description_short: Документы и новости организации и сообщества в целом.

keywords: промышленный альпинизм, промальп, промальпинизм, высотные работы, професиональный союз, профсоюз, rope access

email: profalp@goodclimbers.ru
twitter: profalprussia

baseurl: "/"
url: "http://profalp.goodclimbers.ru"

markdown: kramdown

source:       .
destination:  deploy

timezone: Europe/Moscow

lessc: /home/cat/.npm-global/bin/lessc

kramdown:
    auto_ids: false
